; Catena's Simplified Chinese wizard messages. Other messages inherit Inno's defaults.
[LangOptions]
LanguageName=简体中文
LanguageID=$0804
LanguageCodePage=936
DialogFontName=Microsoft YaHei UI
DialogFontSize=9

[Messages]
SetupAppTitle=安装
SetupWindowTitle=安装 %1
UninstallAppTitle=卸载
UninstallAppFullTitle=卸载 %1
InformationTitle=说明
ConfirmTitle=确认
ErrorTitle=错误
SetupLdrStartupMessage=即将安装 %1，是否继续？
SetupFileCorrupt=安装文件已损坏，请重新下载安装包
SetupAlreadyRunning=安装程序已经在运行
AdminPrivilegesRequired=安装搜索服务需要管理员权限，请允许 Windows 的安装请求
ExitSetupTitle=退出安装
ExitSetupMessage=安装尚未完成。现在退出将中止安装，之后可重新运行安装包。%n%n是否退出？
ButtonBack=< 上一步(&B)
ButtonNext=下一步(&N) >
ButtonInstall=安装(&I)
ButtonOK=确定
ButtonCancel=取消
ButtonYes=是(&Y)
ButtonNo=否(&N)
ButtonFinish=完成(&F)
ButtonBrowse=浏览(&B)…
ButtonWizardBrowse=浏览(&R)…
SelectLanguageTitle=选择安装语言
SelectLanguageLabel=请选择安装向导使用的语言
ClickNext=点击「下一步」继续，或点击「取消」退出
WelcomeLabel1=欢迎安装 [name]
WelcomeLabel2=将安装 [name/ver] 及所需的搜索组件。
WizardLicense=许可协议
LicenseLabel=继续前请阅读以下许可说明
LicenseLabel3=请阅读许可协议，接受后即可继续安装
LicenseAccepted=我接受协议(&A)
LicenseNotAccepted=我不接受协议(&D)
WizardInfoBefore=安装说明
InfoBeforeLabel=搜索组件将随 Catena 一起准备
InfoBeforeClickLabel=阅读后点击「下一步」继续
WizardSelectDir=安装位置
SelectDirDesc=将 [name] 安装到哪个文件夹？
SelectDirLabel3=安装程序将使用以下文件夹
SelectDirBrowseLabel=可直接使用默认位置。需要更改时点击「浏览」
DiskSpaceGBLabel=至少需要 [gb] GB 可用空间
DiskSpaceMBLabel=至少需要 [mb] MB 可用空间
WizardReady=准备安装
ReadyLabel1=现在可以开始安装 [name]
ReadyLabel2a=点击「安装」继续；点击「上一步」可修改设置
ReadyLabel2b=点击「安装」继续
ReadyMemoDir=安装位置：
ReadyMemoGroup=开始菜单：
WizardPreparing=准备安装
PreparingDesc=正在准备 [name] 和搜索组件
CannotContinue=无法继续安装，请点击「取消」退出
ApplicationsFound=以下程序正在使用需要更新的文件，请先关闭这些程序
CloseApplications=自动关闭这些程序(&A)
DontCloseApplications=暂不关闭(&D)
WizardInstalling=正在安装
InstallingLabel=正在安装 [name]，请稍候
FinishedHeadingLabel=[name] 安装完成
FinishedLabelNoIcons=[name] 已安装到电脑
FinishedLabel=[name] 已安装。可从开始菜单启动应用
ClickFinish=点击「完成」关闭安装向导
RunEntryExec=启动 %1
SetupAborted=安装未完成。解决问题后可重新运行安装包
StatusClosingApplications=正在关闭程序…
StatusCreateDirs=正在创建文件夹…
StatusExtractFiles=正在复制文件…
StatusCreateIcons=正在创建快捷方式…
StatusCreateRegistryEntries=正在写入安装信息…
StatusSavingUninstall=正在保存卸载信息…
StatusRunProgram=正在完成安装…
StatusRollback=正在撤销更改…
